### ISSUE TITLE
Is there a way to use `UniqueCommentTextProvider` in `SettingsViewController`

### ISSUE THREAD

**Issue by 10000TB** [DianQK/Flix#16]
First, Great work!! 
New to this, and have a quick question regarding the example provided:

In `Do Not Disturb` VC, there is this `UniqueCommentTextProvider`, how can that be used in `SettingsViewController` ? (it does not allow now as the former is a collection view cell, while the latter is mainly on a tableview) - so the question could also be: how to write a similar `UniqueCommentTextProvider` for collectionviewcell ?
Thanks ahead!!

**Comment by DianQK** [comment]
hmm?
now `UniqueCommentTextProvider` is used for `UICollectionView`. If you want to add `UniqueCommentTextProvider` to `UITableViewCell`，we can use `SingleTableViewCellProvider`, `SingleUITableViewCellProvider` or `AnimatablePartionSectionTableViewProvider`.

for example:

```swift
class SingleCommentTextTableViewProvider: SingleUITableViewCellProvider {

    let textLabel = UILabel()

    override init() {
        super.init()
        ...
    }

}
``` 

If you want to create `UniqueCommentTextProvider` for `UITableView` & `UICollectionView`, this is maybe not support. Maybe you need add more wrap class.
But I will think about this feature on 3.x. (maybe not, because `UITableView` and `UICollectionView` have different method).

**Comment by 10000TB** [comment]
Thanks @DianQK .
I was trying to do that by subclassing `SingleUITableViewCellProvider `, but it seems that it does not have `sizeForItemAt` as `SingleUICollectionViewCellProvider` has to set appropriate height.

**Comment by 10000TB** [comment]
Correct me if i am wrong :) :
I am guessing that `SingleUITableViewCellProvider` is missing a function, like `sizeForItem: atIndexPath:` or `heightForItem: atIndexPath`, which needs to set `open var itemHeight: ((UITableView) -> CGFloat?)?` based on cell index, and the height of actual string in the cell label.

**Comment by DianQK** [comment]
Hi @10000TB ,
When we use `SingleUITableViewCellProvider`, I think we can ignore `IndexPath`. But if you need, just override `func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath, value: SingleTableViewCellProvider) -> CGFloat?`.

You can see this implement on `SingleUITableViewCellProvider`:

```swift
open func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath, value: SingleTableViewCellProvider) -> CGFloat? {
    return self.itemHeight?(tableView)
}
```
